export { default as Header } from './Header'
export { default as Main } from './Main'
export { default as Partners } from './Partners'
export { default as Footer } from './Footer'
export { default as Message } from './Message'
export { default as ShakeTitle } from './ShakeTitle'
